### ISSUE TITLE
I can't run implementation

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [jonlwowski012/OV7670_NEXYS4_Verilog#1]
When I copy all the file into my new project, I can run the synthesis successfully, however, I can't run the implementation. It throws an error:

[DRC INBB-3] Black Box Instances: Cell 'fb1' of type 'fb1/frame_buffer' has undefined contents and is considered a black box.  The contents of this cell must be defined for opt_design to complete successfully.

What's wrong? Looking forward to your reply.

**Comment by jonlwowski012** [comment]
This link may help.

https://forums.xilinx.com/t5/Welcome-Join/Specify-a-module-as-black-box-in-Vivado-Synthesis/td-p/642510
